# =============================================================================
# KUBE-STATE-METRICS - DEPLOYMENT
# =============================================================================
{{- if .Values.kubeStateMetrics.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kubeStateMetrics.label }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kubeStateMetrics.label }}
    component: metrics
spec:
  replicas: {{ .Values.kubeStateMetrics.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kubeStateMetrics.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.kubeStateMetrics.label }}
        component: metrics
    spec:
      serviceAccountName: {{ .Values.kubeStateMetrics.label }}
      containers:
        - name: {{ .Values.kubeStateMetrics.label }}
          image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
          imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
          args:
            - --port=8080
            - --telemetry-port=8081
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
            - containerPort: 8081
              name: telemetry
              protocol: TCP
          resources:
            {{- toYaml .Values.kubeStateMetrics.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubeStateMetrics.label }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kubeStateMetrics.label }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
    - name: http-metrics
      port: {{ .Values.kubeStateMetrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
    - name: telemetry
      port: {{ .Values.kubeStateMetrics.service.metricsPort }}
      targetPort: telemetry
      protocol: TCP
  selector:
    app: {{ .Values.kubeStateMetrics.label }}
{{- end }}
