{{- if .Values.notification.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-hpa" .Values.notification.label }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-depl" .Values.notification.label }}  
  minReplicas: {{ .Values.notification.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.notification.autoscaling.maxReplicas | default 3 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.notification.autoscaling.targetCPUUtilization | default 70 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.notification.autoscaling.targetMemoryUtilization | default 80 }}
{{- end }}