apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-depl" .Values.web.label }}  
  labels:
    app: {{ .Values.web.label }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.label }}
    spec:
      containers:
        - name: {{ printf "%s-container" .Values.web.label }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.web.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.web.resources.requests.cpu }}
              memory: {{ .Values.web.resources.requests.memory }}
            limits:
              cpu: {{ .Values.web.resources.limits.cpu }}
              memory: {{ .Values.web.resources.limits.memory }}            