apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.rootUsername | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.rootPassword | b64enc }}
