apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.mongodb.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
  type: ClusterIP
